"""Product repository for data access."""

from sqlmodel import Session

from .entity import Product
from .table import ProductTable


class ProductRepository:
    """Data access layer for Product entities.

    This handles all database operations for Products while keeping
    the data access logic colocated with the Product entity.
    """

    def __init__(self, session: Session) -> None:
        self._session = session

    def get(self, product_id: str) -> Product | None:
        """Get a product by ID."""
        row = self._session.get(ProductTable, product_id)
        if row is None:
            return None
        return Product.model_validate(row, from_attributes=True)

    def create(self, product: Product) -> Product:
        """Create a new product and return it. ID is auto-generated by the entity."""
        row = ProductTable.model_validate(product, from_attributes=True)
        self._session.add(row)
        return product  # No need for flush/refresh - entity already has its ID!

    def update(self, product: Product) -> Product:
        """Update an existing product."""
        row = self._session.get(ProductTable, product.id)
        if row is None:
            raise ValueError(f"Product with ID {product.id} not found")

        # Update the row with new values
        for field, value in product.model_dump().items():
            setattr(row, field, value)

        return product

    def delete(self, product_id: str) -> bool:
        """Delete a product by ID. Returns True if deleted, False if not found."""
        row = self._session.get(ProductTable, product_id)
        if row is None:
            return False
        self._session.delete(row)
        return True

    def list_all(self) -> list[Product]:
        """List all products."""
        rows = self._session.query(ProductTable).all()
        return [Product.model_validate(row, from_attributes=True) for row in rows]