version: "3.5"
services:
  postgresql:
    container_name: api-template-temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:16
    networks:
      - dev-network
    expose:
      - 5432
    volumes:
      - api-template-temporal-postgres-data:/var/lib/postgresql/data
  temporal:
    container_name: api-template-temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/auto-setup:1.28.1
    networks:
      - dev-network
    ports:
      - 7234:7233
  temporal-ui:
    container_name: api-template-temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.34.0
    networks:
      - dev-network
    ports:
      - 8081:8080

volumes:
  api-template-temporal-postgres-data:
    name: api-template-temporal-postgres-data

networks:
  dev-network:
    external: true

volumes:
  api-template-temporal-postgres-data:
    name: api-template-temporal-postgres-data

networks:
  dev-network:
    external: true