version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --http-port=8080 --log-level=INFO
    user: "1000:1000"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-data:/opt/keycloak/data/
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/8080'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge