# Temporal Development Configuration
# This file contains dynamic configuration for Temporal in development mode

# Default namespace settings
system.enableNamespaceNotActiveAutoForwarding:
- value: true

# History service settings
history.maxAutoResetPoints:
- value: 20

# Visibility settings
system.visibilityTaskBatchSize:
- value: 100

# Frontend settings
frontend.enableClientVersionCheck:
- value: false

# Worker settings
worker.stickyCacheSize:
- value: 10000

# Development specific settings
system.enableLoggerRateLimiting:
- value: false

# Debugging
system.enableDebugMode:
- value: true