name: Template Update Check

on:
  schedule:
    # Check for template updates weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  check-template-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '{{cookiecutter.python_version}}'

      - name: Install cruft
        run: |
          python -m pip install --upgrade pip
          pip install cruft

      - name: Check for template updates
        id: cruft-check
        run: |
          echo "Checking for template updates..."
          if cruft check; then
            echo "template-updated=false" >> $GITHUB_OUTPUT
            echo "✅ Template is up to date"
          else
            echo "template-updated=true" >> $GITHUB_OUTPUT
            echo "📋 Template updates available"
          fi

      - name: Create update branch
        if: steps.cruft-check.outputs.template-updated == 'true'
        run: |
          # Create a new branch for the update
          BRANCH_NAME="template-update-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          echo "UPDATE_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Apply template updates
        if: steps.cruft-check.outputs.template-updated == 'true'
        run: |
          echo "Applying template updates..."
          cruft update --skip-apply-ask || true
          
          # Check if there are any changes
          if git diff --quiet; then
            echo "No changes after cruft update"
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          else
            echo "Changes detected after cruft update"
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: steps.cruft-check.outputs.template-updated == 'true' && env.HAS_CHANGES == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all changes
          git add .
          
          # Create commit with template info
          TEMPLATE_COMMIT=$(cruft status | grep "commit" | cut -d' ' -f2 | head -n1)
          git commit -m "feat: update from template

          Applied template updates from commit: $TEMPLATE_COMMIT
          
          This automated update was generated by the template-update workflow.
          Please review changes carefully before merging.
          
          To resolve conflicts:
          1. Review the changes in this PR
          2. Test the application thoroughly  
          3. Update any custom code that conflicts
          4. Merge when ready
          
          For more info on template updates: https://cruft.github.io/cruft/"
          
          # Push the branch
          git push origin "$UPDATE_BRANCH"

      - name: Create Pull Request
        if: steps.cruft-check.outputs.template-updated == 'true' && env.HAS_CHANGES == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔄 Template Update Available',
              head: process.env.UPDATE_BRANCH,
              base: 'main',
              body: `## 🔄 Template Update

            This PR contains updates from the [FastAPI Hexagonal Template]({{cookiecutter._template}}).

            ### What's included
            - ✅ Latest template improvements
            - ✅ Updated dependencies (if any)
            - ✅ Configuration updates
            - ✅ Documentation updates

            ### Before merging
            - [ ] Review all changes carefully
            - [ ] Test the application locally
            - [ ] Update any conflicting custom code
            - [ ] Verify tests pass
            - [ ] Check that configuration is correct

            ### Template Update Process
            This update was automatically generated using [Cruft](https://cruft.github.io/cruft/).

            #### Manual update process (if needed):
            \`\`\`bash
            # Check for updates
            cruft check

            # Apply updates interactively
            cruft update

            # Review and test changes
            pytest
            \`\`\`

            ### 📚 Migration Guide
            Check the template's [MIGRATING.md]({{cookiecutter._template}}/blob/main/MIGRATING.md) for any breaking changes or migration steps.

            ---
            *This PR was automatically created by the template-update workflow.*`
            });

            console.log(\`Created PR #\${pr.number}: \${pr.html_url}\`);

      - name: No updates available
        if: steps.cruft-check.outputs.template-updated == 'false'
        run: |
          echo "✅ No template updates available. Your project is up to date!"