version: "3.8"

services:
  postgres:
    container_name: app_dev_postgres_db
    image: postgres:16-alpine
    env_file:
      - ../../../.env
    environment:
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - dev-network

volumes:
  postgres_data_dev:
    driver: local

networks:
  dev-network:
    name: dev-network
    driver: bridge