apiVersion: v1
data:
  csrf-signing-secret: alBuWVdWakNVcWxtTmlGVlV1U0FaWmZDdnYrY3AyaUpRRmd3d1FTTlBQST0=
kind: Secret
metadata:
  labels:
    io.kompose.service: csrf-signing-secret
  name: csrf-signing-secret
type: Opaque
