apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml -o k8s-out/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: postgres-verifier
  name: postgres-verifier
spec:
  containers:
    - args:
        - -ec
        - |
          set -euo pipefail
          export PGPASSWORD="$()(cat /run/secrets/postgres_app_user_pw)"      # APP_USER for most checks
          export PGSU_PASSWORD="$()(cat /run/secrets/postgres_password)"      # ⬅️ superuser just for pg_hba checks
          exec /verify.sh
      command:
        - /bin/sh
      envFrom:
        - configMapRef:
            name: env
      image: postgres:15
      name: postgres-verifier
      volumeMounts:
        - mountPath: /run/secrets
          name: postgres-app-user-pw
          subPath: postgres-app-user-pw
        - mountPath: /run/secrets
          name: postgres-password
          subPath: postgres-password
        - mountPath: /verify.sh
          name: postgres-verifier-cm0
          readOnly: true
          subPath: verify.sh
  restartPolicy: Never
  volumes:
    - name: postgres-app-user-pw
      secret:
        items:
          - key: postgres-app-user-pw
            path: postgres-app-user-pw
        secretName: postgres-app-user-pw
    - name: postgres-password
      secret:
        items:
          - key: postgres-password
            path: postgres-password
        secretName: postgres-password
    - configMap:
        items:
          - key: verify-init.sh
            path: verify.sh
        name: postgres-verifier-cm0
      name: postgres-verifier-cm0
