apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: redis-backups
  name: redis-backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
