apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml -o k8s-out/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: temporal-schema-setup
  name: temporal-schema-setup
spec:
  containers:
    - args:
        - /schema-setup.sh
      command:
        - /bin/sh
        - -lc
      env:
        - name: EP
          value: postgres
        - name: PW_FILE
          value: /run/secrets/postgres-temporal-pw
        - name: SSL_MODE
          value: verify-ca
        - name: TEMPORAL_DB
          value: temporal
        - name: TEMPORAL_DB_USER
          value: temporaluser
        - name: TEMPORAL_VIS_DB
          value: temporal_visibility
        - name: TLS_CA_FILE
          value: /run/secrets/postgres-server-ca
        - name: TLS_ENABLE
          value: "true"
      image: temporalio/admin-tools:1.29.0-tctl-1.18.4-cli-1.4.2
      name: api-template-temporal-schema-setup-prod
      volumeMounts:
        - mountPath: /run/secrets
          name: postgres-temporal-pw
          subPath: postgres-temporal-pw
        - mountPath: /run/secrets
          name: postgres-server-ca
          subPath: postgres-server-ca
        - mountPath: /schema-setup.sh
          name: temporal-schema-setup-cm0
          readOnly: true
          subPath: schema-setup.sh
  restartPolicy: Never
  volumes:
    - name: postgres-temporal-pw
      secret:
        items:
          - key: postgres-temporal-pw
            path: postgres-temporal-pw
        secretName: postgres-temporal-pw
    - name: postgres-server-ca
      secret:
        items:
          - key: postgres-server-ca
            path: postgres-server-ca
        secretName: postgres-server-ca
    - configMap:
        items:
          - key: schema-setup.sh
            path: schema-setup.sh
        name: temporal-schema-setup-cm0
      name: temporal-schema-setup-cm0
