apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml -o k8s-out/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: temporal-namespace-init
  name: temporal-namespace-init
spec:
  containers:
    - args:
        - sh
        - -lc
        - |2
            set -e
            echo "[init] waiting for cluster health...";
            for i in $()(seq 1 60); do
              temporal --command-timeout 2s operator cluster health && break || sleep 2
            done
            echo "[init] describing namespace...";
            if temporal operator namespace describe -n default >/dev/null 2>&1; then
              echo "[init] namespace already exists";
            else
              echo "[init] creating namespace...";
              temporal operator namespace create -n default --retention 7d
              echo "[init] created";
            fi
      env:
        - name: TEMPORAL_ADDRESS
          value: temporal:7233
      image: temporalio/admin-tools:1.29.0-tctl-1.18.4-cli-1.4.2
      name: api-template-temporal-namespace-init-prod
  restartPolicy: Never
