apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: temporal-certs
  name: temporal-certs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
