"""User repository for data access."""

from sqlmodel import Session

from .entity import User
from .table import UserTable


class UserRepository:
    """Data access layer for User entities.

    This handles all database operations for Users while keeping
    the data access logic colocated with the User entity.
    """

    def __init__(self, session: Session) -> None:
        self._session = session

    def get(self, user_id: str) -> User | None:
        """Get a user by ID."""
        row = self._session.get(UserTable, user_id)
        if row is None:
            return None
        return User.model_validate(row, from_attributes=True)

    def create(self, user: User) -> User:
        """Create a new user and return it. ID is auto-generated by the entity."""
        row = UserTable.model_validate(user, from_attributes=True)
        self._session.add(row)
        return user  # No need for flush/refresh - entity already has its ID!
