version: "3.8"

services:
  temporal-postgresql:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
      POSTGRES_DB: temporal
    volumes:
      - temporal_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-network

  temporal-server:
    image: temporalio/auto-setup:1.24.2
    ports:
      - "7233:7233"
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgresql
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal-server:7233", "cluster", "health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - dev-network

  temporal-web:
    image: temporalio/ui:2.28.0
    ports:
      - "8088:8088"
    environment:
      - TEMPORAL_ADDRESS=temporal-server:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    networks:
      - dev-network

volumes:
  temporal_postgres_data:
    name: api-template-temporal-postgres-data
  temporal_data:
    name: api-template-temporal-data

networks:
  dev-network:
    external: true
    name: dev-network