version: "3.8"

services:
  keycloak:
    extends:
      file: keycloak/docker-compose.yml
      service: keycloak

  postgres:
    extends:
      file: postgres/docker-compose.yml
      service: postgres

volumes:
  keycloak_data:
    driver: local
  postgres_data:
    driver: local

networks:
  dev-network:
    name: dev-network
    driver: bridge