version: "3.8"

services:
  keycloak:
    extends:
      file: keycloak/docker-compose.yml
      service: keycloak

  postgres:
    extends:
      file: postgres/docker-compose.yml
      service: postgres

networks:
  dev-network:
    name: dev-network
    driver: bridge