"""Book repository for data access."""

from sqlmodel import Session

from .entity import Book
from .table import BookTable


class BookRepository:
    """Data access layer for Book entities.

    This handles all database operations for Books while keeping
    the data access logic colocated with the Book entity.
    """

    def __init__(self, session: Session) -> None:
        self._session = session

    def get(self, book_id: str) -> Book | None:
        """Get a book by ID."""
        row = self._session.get(BookTable, book_id)
        if row is None:
            return None
        return Book.model_validate(row, from_attributes=True)

    def create(self, book: Book) -> Book:
        """Create a new book and return it. ID is auto-generated by the entity."""
        row = BookTable.model_validate(book, from_attributes=True)
        self._session.add(row)
        return book  # No need for flush/refresh - entity already has its ID!

    def update(self, book: Book) -> Book:
        """Update an existing book."""
        row = self._session.get(BookTable, book.id)
        if row is None:
            raise ValueError(f"Book with ID {book.id} not found")

        # Update the row with new values
        for field, value in book.model_dump().items():
            setattr(row, field, value)

        return book

    def delete(self, book_id: str) -> bool:
        """Delete a book by ID. Returns True if deleted, False if not found."""
        row = self._session.get(BookTable, book_id)
        if row is None:
            return False
        self._session.delete(row)
        return True

    def list_all(self) -> list[Book]:
        """List all books."""
        rows = self._session.query(BookTable).all()
        return [Book.model_validate(row, from_attributes=True) for row in rows]